apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - image: galkin/k8s-ui
          name: ui
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 80
        - image: galkin/k8s-server
          name: server
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
  name: chat
spec:
  type: LoadBalancer
  selector:
    app: chat
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80