apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      role: frontend
  template:
    metadata:
      labels:
        app: chat
        role: frontend
    spec:
      containers:
        - image: galkin/k8s-ui
          name: ui
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      role: backend
  template:
    metadata:
      labels:
        app: chat
        role: backend
    spec:
      containers:
        - image: galkin/k8s-server
          name: server
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
spec:
  selector:
    app: chat
    role: backend
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
spec:
  selector:
    app: chat
    role: frontend
  ports:
    - name: default
      protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer